# Generated by Django 4.0.4 on 2022-05-20 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tags',
            new_name='tag',
        ),
    ]
