# Generated by Django 4.0.4 on 2022-05-25 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='course_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
